services:
    _defaults:
        autowire: true
        autoconfigure: true

    # DE: Alle Bundle-Services auto-registrieren (skalare Params via #[Autowire])
    # EN: Auto-register all bundle services (scalar params via #[Autowire])
    Jostkleigrewe\Sso\Bundle\:
        resource: '../src/Bundle/'
        exclude:
            - '../src/Bundle/EuripSsoBundle.php'
            - '../src/Bundle/OidcConstants.php'
            - '../src/Bundle/Factory/'
            - '../src/Bundle/Event/'
            - '../src/Bundle/Security/OidcUser.php'
            - '../src/Bundle/Security/OidcUserProviderInterface.php'
            - '../src/Bundle/Security/DoctrineOidcUserProvider.php'
            - '../src/Bundle/Security/OidcAuthenticator.php'
