services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Security Authenticator
    Jostkleigrewe\Sso\Bundle\Security\OidcAuthenticator:
        arguments:
            $callbackRoute: '%eurip_sso.authenticator.callback_route%'
            $defaultTargetPath: '%eurip_sso.authenticator.default_target_path%'
            $loginPath: '%eurip_sso.authenticator.login_path%'

    # Console Commands
    Jostkleigrewe\Sso\Bundle\Command\OidcCacheWarmupCommand:
        arguments:
            $cacheTtl: '%eurip_sso.cache.ttl%'
        tags:
            - { name: console.command }
